version: '3.4'

services:
  ecommerce.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ecommerce.customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.reporting.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.sales.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

