version: '3.4'

services:
  ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY}ecommerce/catalog.api
    build:
      context: .
      dockerfile: Services/ECommerce.Catalog.Api/Dockerfile

  ecommerce.customers.api:
    image: ${DOCKER_REGISTRY}ecommerce/customers.api
    build:
      context: .
      dockerfile: Services/ECommerce.Customers.Api/Dockerfile


  ecommerce.logging.host:
    image: ${DOCKER_REGISTRY}ecommerce/logging.host
    build:
      context: .
      dockerfile: Services/ECommerce.Logging.Host/Dockerfile


  ecommerce.payment.host:
    image: ${DOCKER_REGISTRY}ecommerce/payment.host
    build:
      context: .
      dockerfile: Services/ECommerce.Payment.Host/Dockerfile


  ecommerce.reporting.api:
    image: ${DOCKER_REGISTRY}ecommerce/reporting.api
    build:
      context: .
      dockerfile: Services/ECommerce.Reporting.Api/Dockerfile


  ecommerce.sales.api:
    image: ${DOCKER_REGISTRY}ecommerce/sales.api
    build:
      context: .
      dockerfile: Services/ECommerce.Sales.Api/Dockerfile


  ecommerce.shipping.host:
    image: ${DOCKER_REGISTRY}ecommerce/shipping.host
    build:
      context: .
      dockerfile: Services/ECommerce.Shipping.Host/Dockerfile

